CRM/CRM.WebApp/Models/Applications/Complaint.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace CRM.WebApp.Models.Applications
{
    public class Complaint
    {
        /// <summary>
        /// Id
        /// </summary>
        [DisplayName("Id")]
        public int ComplaintId { get; set; }

        /// <summary>
        /// Title
        /// </summary>
        [Required]
        [StringLength(100, MinimumLength=3)]
        [DisplayName("Tytuł")]
        public string Title { get; set; }

        /// <summary>
        /// Time when application been officialy started.
        /// </summary>
        [DisplayName("Czas powstania")]
        public DateTime? CreationTime { get; set; }

        /// <summary>
        /// Time when application been officialy ended.
        /// </summary>
        [DisplayName("Czas zakończenia")]
        public DateTime? EndTime { get; set; }

        [Required]
        [DisplayName("Opis")]
        public string Description { get; set; }

        /// <summary>
        /// Converted to enum ServiceRequestStatus. This property should be used in logic layer. EF6 sucks in some ways.
        /// </summary>
        [NotMapped]
        [DisplayName("Status")]
        public ComplaintStatus Status
        {
            get { return (ComplaintStatus)Enum.Parse(typeof(ComplaintStatus), !string.IsNullOrEmpty(ComplaintStatus) ? ComplaintStatus : CRM.WebApp.Models.Applications.ComplaintStatus.Await.ToString()); }
            set { ComplaintStatus = value.ToString(); }
        }

        /// <summary>
        /// Used only for mapping. Converted to Status property;
        /// </summary>
        public string ComplaintStatus { get; set; } // Must be public!
    }

    public enum ComplaintStatus
    {
        Canceled = 0, Await = 1, Solved = 2, InProgress = 3
    }
}

CRM/CRM.WebApp/Controllers/ComplaintController.cs
using CRM.WebApp.Models.Applications;
using CRM.WebApp.Mixins;
using CRM.WebApp.Models;
using CRM.WebApp.Infrastructure;
using CRM.WebApp.Infrastructure;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace CRM.WebApp.Controllers
{
    public class ComplaintController : Controller
    {
        /// <summary>
        /// Data access object
        /// </summary>
        public CrmDbContext _db;

        /// <summary>
        /// If you don't know where you should redirect, use this field.
        /// </summary>
        public static string DefaultRedirectAction { get; set; }

        /// <summary>
        /// Constructor
        /// </summary>
        public ComplaintController()
        {
            // Initilize variables 

            if (_db == null)
            {
                _db = new CrmDbContext();
            }

            DefaultRedirectAction = "List";
        }

        //
        // GET: /Complaints/
        public ActionResult Index()
        {
            return RedirectToAction(DefaultRedirectAction);
        }

        //
        // GET: /Complaints/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Complaints/Create
        [HttpPost]
        public ActionResult Create(Complaint complaint)
        {
            if (ModelState.IsValid)
            {
                // Set complaints creation time to this moment.
                complaint.CreationTime = DateTime.Now;

                _db.Complaints.Add(complaint);
                _db.SaveChanges();

                this.ShowNotification(NotificationType.Success, "Reklamacja została pozytywnie dodana.", true);
                return RedirectToAction("List");
            }

            this.ShowNotification(NotificationType.Warning, "Coś poszło nie tak. Reklamacja nie została dodana.");
            return View();
        }

        // GET: /Complaints/List
        public ActionResult List()
        {
            if (_db.IsNull())
                throw new NullReferenceException("Database context is null!");

            IEnumerable<Complaint> complaints = _db.Complaints;

            if (complaints.Count() == 0)
                this.ShowNotification(NotificationType.Info, "Nie dodano jeszcze żadnych reklamacji.");

            return View(complaints);
        }

        //
        // GET: /Complaints/Edit/5
        public ActionResult Edit(int id)
        {
            Complaint complaint = null;
            complaint = _db.Complaints.First(r => r.ComplaintId == id);
            return View(complaint);
        }

        //
        // POST: /Complaints/Edit
        [HttpPost]
        public ActionResult Edit(Complaint complaint)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(complaint).State = EntityState.Modified;
                _db.SaveChanges();

                this.ShowNotification(NotificationType.Success, "Reklamacja została zmieniona.", true);

                // Redirect to service request details view
                return RedirectToAction("Details", new { id = complaint.ComplaintId });
            }

            this.ShowNotification(NotificationType.Warning, "Coś poszło nie tak. Reklamacja nie została zmieniona.");

            // If received request is not valid, show edit view again for necessery corrections.
            return View(complaint);
        }

        //
        // GET: /Complaints/Details/5
        public ActionResult Details(int id)
        {
            RedirectToRouteResult redirectResult;
            Complaint complaint = FindComplaintInDb(id, out redirectResult);

            if (!redirectResult.IsNull())
            {
                this.ShowNotification(NotificationType.Warning, "Szukana reklamacja nie została odnaleziona.");
                return redirectResult;
            }
            else
                return View(complaint);
        }

        public ActionResult Delete(int id)
        {
            if (_db.IsNull())
                throw new NullReferenceException("Database context is null!");

            RedirectToRouteResult redirectResult;
            Complaint complaint = FindComplaintInDb(id, out redirectResult);

            if (!redirectResult.IsNull())
            {
                this.ShowNotification(NotificationType.Danger, "Nie można było usunąć danej reklamacji", true);
                return redirectResult;
            }

            // Remove complaint
            _db.Complaints.Remove(complaint);

            // Sync with db
            _db.SaveChanges();

            this.ShowNotification(NotificationType.Success, "Reklamacja została usunięta.", true);

            return RedirectToAction("List");
        }

        /// <summary>
        /// Help method for redirecting when seeked complaint is not found in data storage. Logs down appropriate warn log and redirects to the given action.
        /// </summary>
        /// <param name="id">Seeked complaint id.</param>
        /// <param name="action">Action where will be redirected to.</param>
        private RedirectToRouteResult ComplaintNotFoundRedirect(int id, string action)
        {
            Log.Warn(string.Format("Complaint with Id={0} is was not found and caused the exception. Redirecting to {1}", id, action), this);
            return RedirectToAction(action);
        }

        /// <summary>
        /// Searches database for complaint with same Id.
        /// If complaint isn't found, logs down error and redirects.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="redirectResult"></param>
        /// <returns></returns>
        private Complaint FindComplaintInDb(int id, out RedirectToRouteResult redirectResult)
        {
            Complaint complaint = null;
            redirectResult = null;

            try
            {
                complaint = _db.Complaints.First(c => c.ComplaintId == id);
            }
            catch (InvalidOperationException)
            {
                redirectResult = ComplaintNotFoundRedirect(id, DefaultRedirectAction);
            }

            if (redirectResult.IsNull() && !complaint.IsNull())
                Log.Info(string.Format("Found complaint: {0}", complaint.ToString()), this);

            return complaint;
        }
    }
}

CRM/CRM.WebApp/Views/Complaint/Create.cshtml
@model CRM.WebApp.Models.Applications.Complaint

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3>Tworzenie nowej reklamacji</h3>
        <hr />
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Dane reklamacji</legend>

            @*Title*@
            <div class="form-group">
                @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @id = "title-tb", placeholder="Tytuł reklamacji powinien być ciągiem znaków o długości minimalnej 3 i maksymalnej 100.", @MinLength="3", @MaxLength="100" })
                    @Html.ValidationMessageFor(model => model.Title)
                </div>
            </div>

            @*Description*@
            <div class="form-group">
                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @id = "client-interview-ta", placeholder="Tutaj powinien znajdować się opis reklamacji" , @MaxLength="10000" })
                    @Html.ValidationMessageFor(model => model.Description)
                </div>
            </div>

            @*Status*@
            <div class="row">
                @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @{
    List<SelectListItem> listItems = new List<SelectListItem>(){
                            new SelectListItem(){ Text = "Oczekuje", Value = "Await", Selected = true },
                            new SelectListItem(){ Text = "W trakcie", Value = "InProgress" },
                            new SelectListItem(){ Text = "Rozpatrzone", Value = "Solved" },
                            new SelectListItem(){ Text = "Anulowane", Value = "Canceled" }
                          };
                    }
                    @Html.DropDownListFor(model => model.Status, listItems, "")
                    @*Html.TextBoxFor(Model => Model.PredictedRealizationDate, new { @class = "form-control datepicker", placeholder = "Enter Drop-off date here..." })*@
                </div>
            </div>
            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <input type="reset" value="Wyczyść" class="btn btn-default" /> 
                </div>
            </div>


        </fieldset>
    </div>
}

CRM/CRM.WebApp/Views/Complaint/Details.cshtml
@model CRM.WebApp.Models.Applications.Complaint

@{
    ViewBag.Title = "Szczegóły reklamacji";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<ul class="nav nav-pills nav-justified">
    <li class="active"><a href='@Url.Action("List", "Complaint")'>Wróć</a></li>
    <li><a href='@Url.Action("Edit", "Complaint", new { id = Model.ComplaintId })'>Edytuj</a></li>
    <li><a href='@Url.Action("Delete", "Complaint", new { id = Model.ComplaintId }, new { @onclick = "return confirm('Czy jesteś pewny, że chcesz usnunąć ?')" })'>Usuń</a></li>
</ul>
<br />

<div class="panel panel-primary">

    <div class="panel-heading">
        <h3 class="panel-title"><strong>Szczegółowe informacje</strong></h3>
    </div>

    <table class="table">
        <tr>
            <td><strong>@Html.DisplayNameFor(model => model.Title)</strong></td>

            <td> @Html.DisplayFor(model => model.Title) </td> @*Required*@
        </tr>

        <tr>
            <td><strong> Klient </strong></td>

            <td></td> @*?Required?*@
        </tr>

        <tr>
            <td><strong> @Html.DisplayNameFor(model => model.ComplaintId) </strong></td>

            <td> @Html.DisplayFor(model => model.ComplaintId) </td>
        </tr>

        <tr>
            @if (Model.ComplaintStatus.Equals("Solved"))
            {
                <td><strong> @Html.DisplayNameFor(model => model.EndTime) </strong></td>

                <td>
                    @if (!Model.EndTime.HasValue)
                    {
                        <em><small>Brak informacji</small></em>
                    }
                    else
                    {
                        @Html.DisplayFor(model => model.EndTime)
                    }
                </td>
            }
            else
            {

            <tr>
                <td><strong> @Html.DisplayNameFor(model => model.CreationTime) </strong></td>

                <td>
                    @if (!Model.CreationTime.HasValue)
                    {
                        <em><small>Brak informacji</small></em>
                    }
                    else
                    {
                        @Html.DisplayFor(model => model.CreationTime) @*nie powinno być Required?*@
                    }
                </td>
            </tr>
            }
            </tr>

            <tr>
                <td><strong> @Html.DisplayNameFor(model => model.Status) </strong></td>

                <td> @Html.DisplayFor(model => model.Status) </td> @*Required*@
            </tr>
        </table>
    </div>

    @*Description*@
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">
                <strong> @Html.DisplayNameFor(model => model.Description) </strong>
            </h3>
        </div>

        <div class="panel-body">
            @Html.DisplayFor(model => model.Description) @*Required*@
        </div>
    </div>

CRM/CRM.WebApp/Views/Complaint/Edit.cshtml
@model CRM.WebApp.Models.Applications.Complaint

@{
    ViewBag.Title = "Edycja reklamacji";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3>@ViewBag.Title</h3>
        <hr />
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Dane reklamacji</legend>

            @Html.HiddenFor(model => model.ComplaintId)

            @*Title*@
            <div class="form-group">
                @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @id = "title-tb" })
                    @Html.ValidationMessageFor(model => model.Title)
                </div>
            </div>

            @*Description*@
            <div class="form-group">
                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @id = "client-interview-ta" })
                    @Html.ValidationMessageFor(model => model.Description)
                </div>
            </div>

            @*Status*@
            <div class="row">
                @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @{
    List<SelectListItem> listItems = new List<SelectListItem>(){
                            new SelectListItem(){ Text = "Oczekuje", Value = "Await", Selected = true },
                            new SelectListItem(){ Text = "W trakcie", Value = "InProgress" },
                            new SelectListItem(){ Text = "Rozpatrzone", Value = "Solved" },
                            new SelectListItem(){ Text = "Anulowane", Value = "Canceled" }
                          };
                    }
                    @Html.DropDownListFor(model => model.Status, listItems, "")
                    @*Html.TextBoxFor(Model => Model.PredictedRealizationDate, new { @class = "form-control datepicker", placeholder = "Enter Drop-off date here..." })*@
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>


        </fieldset>
    </div>
}

CRM/CRM.WebApp/Views/Complaint/List.cshtml
@model IEnumerable<CRM.WebApp.Models.Applications.Complaint>

@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista reklamacji</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ComplaintId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreationTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ComplaintId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreationTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink(" ", "Delete", new { id = item.ComplaintId }, new { @class = "usun", @onclick = "return confirm('Czy jesteś pewny, że chcesz usnunąć ?')" })
        </td>
        <td>
            @Html.ActionLink(" ", "Details", new { id=item.ComplaintId }, new { @class = "pokaz"  })
        </td>
        <td>
            @Html.ActionLink(" ", "Edit", new { id = item.ComplaintId }, new { @class = "edytuj" })
        </td>
    </tr>
}

</table>